---
title: "R Notebook"
output: html_notebook
---

```{r}
#Implementing NN in R
# input matrix
X=matrix(c(1,0,1,0,1,0,1,1,0,1,0,1),nrow = 3, ncol=4,byrow = TRUE)

# output matrix
Y=matrix(c(1,0,0),byrow=FALSE)
```

```{r}
#sigmoid function
sigmoid<-function(x){
1/(1+exp(-x))
}

# derivative of sigmoid function
derivatives_sigmoid<-function(x){
x*(1-x)
}
```

```{r}
# variable initialization
epoch=10000 #number of iteration
lr=0.5
inputlayer_neurons=ncol(X)
hiddenlayer_neurons=5
output_neurons=1
```


```{r}
#weight and bias initialization
wh=matrix(rnorm(inputlayer_neurons*hiddenlayer_neurons,mean=0,sd=1), inputlayer_neurons, hiddenlayer_neurons) #create a inputlayer_neurons x  hiddenlayer_neurons matrix
wh
bias_input=rep(runif(hiddenlayer_neurons), nrow(X))
bh=matrix(bias_input, nrow = nrow(X), byrow = FALSE)
bh

wout=matrix(rnorm(hiddenlayer_neurons*output_neurons,mean=0,sd=1), hiddenlayer_neurons, output_neurons)
wout

bias_output=rep(runif(output_neurons),nrow(X))
bout=matrix(bias_output,nrow = nrow(X),byrow = FALSE)
bout
```


```{r}
# forward propagation
for(i in 1:epoch){


  hidden_layer_input=X%*%wh+bh
  hidden_layer_activations=sigmoid(hidden_layer_input)
  
  output_layer_input=hidden_layer_activations%*%wout+bout
  output= sigmoid(output_layer_input)
  
  # Back Propagation
  
  E=Y-output #loss function
  if (sum(abs(E)) < 0.001){
    print(i)
    break
  }
  slope_output_layer=derivatives_sigmoid(output)
  slope_hidden_layer=derivatives_sigmoid(hidden_layer_activations)
  
  d_output=E*slope_output_layer
  
  Error_at_hidden_layer=d_output%*%t(wout)
  d_hiddenlayer=Error_at_hidden_layer*slope_hidden_layer
  
  wout= wout + (t(hidden_layer_activations)%*%d_output)*lr
  bout= bout+rowSums(d_output)*lr
  
  wh = wh +(t(X)%*%d_hiddenlayer)*lr
  bh = bh + rowSums(d_hiddenlayer)*lr

}
print('Error is:\n')
sum(abs(E))
print('Input is:\n')
X
print('Weights are:\n')
wh
print('Output is:\n')
output
```

```{r}
library(neuralnet)
```

```{r}
df <- data.frame(X,Y)
nn= neuralnet(Y~(X1 + X2 + X3 + X4), 
              data=df, 
              hidden=5,
              threshold = 0.001,
              act.fct = sigmoid,
              learningrate = 0.5,
              linear.output = F)
```

```{r}
plot(nn)
```


```{r}
Predict=compute(nn,df)
Predict
```
